############## RUN ##############
FROM node:22.18.0

WORKDIR /server

ADD ./package.json ./package.json
ADD ./package-lock.json ./package-lock.json
RUN npm install

COPY ./swagger ./swagger
COPY ./src ./src

ENTRYPOINT ["/bin/bash", "-c", "npm start"]
