const CHECKLIST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

const CHALLENGE_TYPE = Object.freeze({
  EXPENSE_COUNT_MORE: 'EXPENSE_COUNT_MORE',
  EXPENSE_COUNT_LESS: 'EXPENSE_COUNT_LESS',
  INCOME_COUNT_MORE: 'INCOME_COUNT_MORE',
  INCOME_COUNT_LESS: 'INCOME_COUNT_LESS',
  EXPENSE_TOTAL_AMOUNT_LESS: 'EXPENSE_TOTAL_AMOUNT_LESS',
  EXPENSE_TOTAL_AMOUNT_MORE: 'EXPENSE_TOTAL_AMOUNT_MORE',
  INCOME_TOTAL_AMOUNT_LESS: 'INCOME_TOTAL_AMOUNT_LESS',
  INCOME_TOTAL_AMOUNT_MORE: 'INCOME_TOTAL_AMOUNT_MORE',
});

const CHALLENGE_PREWARM_LIMITS = [5, 10];

module.exports = {
  CHECKLIST_STATUS,
  CHALLENGE_TYPE,
  CHALLENGE_PREWARM_LIMITS,
};
