const QUEUE_NAMES = {
  CHALLENGE: 'CHALLENGE_QUEUE',
  REPORT: 'REPORT_QUEUE',
};

const JOB_TYPES = {
  CHALLENGE_CHECK_LIST_STATUS_UPDATE: 'CHALLENGE_CHECK_LIST_STATUS_UPDATE',
  GENERATE_MONTHLY_REPORTS: 'GENERATE_MONTHLY_REPORTS',

  GENERATE_TOTAL_INCOME_REPORT: 'GENERATE_TOTAL_INCOME_REPORT',
  GENERATE_TOTAL_EXPENSE_REPORT: 'GENERATE_TOTAL_EXPENSE_REPORT',
  GENERATE_PREV_MONTH_INCOME_CHANGE_REPORT: 'GENERATE_PREV_MONTH_INCOME_CHANGE_REPORT',
  GENERATE_PREV_MONTH_EXPENSE_CHANGE_REPORT: 'GENERATE_PREV_MONTH_EXPENSE_CHANGE_REPORT',
  GENERATE_EXPENSE_RATIO_BY_CATEGORY_REPORT: 'GENERATE_EXPENSE_RATIO_BY_CATEGORY_REPORT',
  GENERATE_INCOME_RATIO_BY_CATEGORY_REPORT: 'GENERATE_INCOME_RATIO_BY_CATEGORY_REPORT',
};

const JOB_TYPE_TO_QUEUE_MAP = {
  [JOB_TYPES.CHALLENGE_CHECK_LIST_STATUS_UPDATE]: QUEUE_NAMES.CHALLENGE,
  [JOB_TYPES.GENERATE_MONTHLY_REPORTS]: QUEUE_NAMES.REPORT,

  [JOB_TYPES.GENERATE_TOTAL_INCOME_REPORT]: QUEUE_NAMES.REPORT,
  [JOB_TYPES.GENERATE_TOTAL_EXPENSE_REPORT]: QUEUE_NAMES.REPORT,
  [JOB_TYPES.GENERATE_PREV_MONTH_INCOME_CHANGE_REPORT]: QUEUE_NAMES.REPORT,
  [JOB_TYPES.GENERATE_PREV_MONTH_EXPENSE_CHANGE_REPORT]: QUEUE_NAMES.REPORT,
  [JOB_TYPES.GENERATE_EXPENSE_RATIO_BY_CATEGORY_REPORT]: QUEUE_NAMES.REPORT,
  [JOB_TYPES.GENERATE_INCOME_RATIO_BY_CATEGORY_REPORT]: QUEUE_NAMES.REPORT,
};

module.exports = {
  QUEUE_NAMES,
  JOB_TYPES,
  JOB_TYPE_TO_QUEUE_MAP,
};
