const QUEUE_NAMES = {
  CHALLENGE: 'CHALLENGE_QUEUE',
};

const JOB_TYPES = {
  CHALLENGE: {
    CHECK_LIST_STATUS_UPDATE: 'CHECK_LIST_STATUS_UPDATE',
  },
};

const JOB_TYPE_TO_QUEUE_MAP = {
  [JOB_TYPES.CHALLENGE.CHECK_LIST_STATUS_UPDATE]: QUEUE_NAMES.CHALLENGE,
};

module.exports = {
  QUEUE_NAMES,
  JOB_TYPES,
  JOB_TYPE_TO_QUEUE_MAP,
};
