const REPORT_TYPE = {
  MONTHLY_TOTAL_INCOME: 'MONTHLY_TOTAL_INCOME',
  MONTHLY_TOTAL_EXPENSE: 'MONTHLY_TOTAL_EXPENSE',

  PREV_MONTH_EXPENSE_CHANGE: 'PREV_MONTH_EXPENSE_CHANGE',
  PREV_MONTH_INCOME_CHANGE: 'PREV_MONTH_INCOME_CHANGE',

  PREV_WEEK_INCOME_CHANGE: 'PREV_WEEK_INCOME_CHANGE',
  PREV_WEEK_EXPENSE_CHANGE: 'PREV_WEEK_EXPENSE_CHANGE',

  EXPENSE_RATIO_BY_CATEGORY: 'EXPENSE_RATIO_BY_CATEGORY',
  INCOME_RATIO_BY_CATEGORY: 'INCOME_RATIO_BY_CATEGORY',

};

const REPORT_UNIT = {
  WON: 'WON',
  PERCENT: 'PERCENT',
  COUNT: 'COUNT',
};

module.exports = {
  REPORT_TYPE,
  REPORT_UNIT,
};
