openapi: 3.0.0
info:
  title: 가계부 서비스
  version: "1.0.0"
  description: 사용자의 수입/지출을 관리하고 분석하는 서비스의 API 명세서.

servers:
  - url: http://localhost:3000
    description: 개발 서버

tags:
  - name: Auth
    description: 사용자 인증 (회원가입, 로그인)
  - name: Users
    description: 사용자 정보 (프로필)
  - name: Incomes
    description: 수입 관리
  - name: Expenses
    description: 지출 관리
  - name: TargetSpendings
    description: 목표 지출 관리
  - name: Reports
    description: 월별 보고서
  - name: Challenges
    description: 도전과제
  - name: ChallengeChecklists
    description: 사용자의 도전과제 참여 현황
  - name: UserLogs
    description: 사용자 활동 로그 (관리자 전용)
  - name: Weather
    description: 날씨 정보
  - name: Health
    description: 서버 상태 확인

paths:
  # --- Health ---
  /api/healthcheck:
    $ref: './paths/health/health.yaml'

  # --- Weather ---
  /api/weather:
    $ref: './paths/weather/weather.yaml'

  # --- Auth ---
  /api/auth/sign-up:
    $ref: './paths/auths/sign-up.yaml'
  /api/auth/sign-in:
    $ref: './paths/auths/sign-in.yaml'
  /api/auth/sign-out:
    $ref: './paths/auths/sign-out.yaml'

  # --- Users ---
  /api/users:
    $ref: './paths/users/users.yaml'
  /api/users/{userId}:
    $ref: './paths/users/user-by-id.yaml'
    
  # --- Incomes ---
  /api/incomes:
    $ref: './paths/incomes/income.yaml'
  /api/incomes/{incomeId}:
    $ref: './paths/incomes/income-by-id.yaml'

  # --- Expenses ---
  /api/expenses:
    $ref: './paths/expenses/expense.yaml'
  /api/expenses/{expenseId}:
    $ref: './paths/expenses/expense-by-id.yaml'
    
  # --- Target Spendings ---
  /api/target-spendings:
    $ref: './paths/target-spendings/target-spending.yaml'
  /api/target-spendings/{targetSpendingId}:
    $ref: './paths/target-spendings/target-spending-by-id.yaml'
    
  # --- Reports ---
  /api/reports:
    $ref: './paths/reports/reports.yaml'

  # --- Challenges ---
  /api/challenges:
    $ref: './paths/challenges/challenge.yaml'
  /api/challenges/{challengeId}:
    $ref: './paths/challenges/challenge-by-id.yaml'

  # --- Challenge Checklists ---
  /api/challenge-checklists:
    $ref: './paths/challenge-checklists/checklists.yaml'
  /api/challenge-checklists/{challengeChecklistId}:
    $ref: './paths/challenge-checklists/checklist-by-id.yaml'

  # --- User Logs ---
  /api/user-logs:
    $ref: './paths/user-logs/logs.yaml'

components:
  schemas:
    $ref: './components/schema.yaml#/schemas'
  parameters:
    $ref: './components/parameter.yaml#/parameters'
  securitySchemes:
    $ref: './components/security-scheme.yaml#/securitySchemes'
