schemas:
  SignUpRequest:
    type: object
    required:
      - email
      - password
      - nickname
      - gender
    properties:
      email:
        type: string
        format: email
        example: 'user@example.com'
      password:
        type: string
        format: password
        example: 'password123!'
      nickname:
        type: string
        example: '가계부사용자1'
      gender:
        type: string
        enum: ['male', 'female']
        example: 'male'
      birthday:
        type: string
        format: date
        example: '2000-07-19'

  SigninRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password

  UpdateUserRequest:
    type: object
    properties:
      nickname:
        type: string
        example: '새로운닉네임'
      gender:
        type: string
        enum: ['male', 'female']
      birthday:
        type: string
        format: date
      newPassword:
        type: string
        format: password
        description: "새로운 비밀번호. 변경을 원할 때만 보냄."
        example: 'newPassword123!'
      newPasswordConfirm:
        type: string
        format: password
        description: "새로운 비밀번호 확인. newPassword와 함께 보내야 함."
        example: 'newPassword123!'

  IncomeRequest:
    type: object
    required:
      - date
      - amount
      - category
    properties:
      date:
        type: string
        format: date
        example: '2025-08-10'
      amount:
        type: integer
        example: 3000000
      category:
        type: string
        enum: ['SALARY', 'SIDE_INCOME', 'ALLOWANCE']
        example: 'SALARY'
      status:
        type: string
        enum: ['APPROVED', 'SCHEDULED', 'REJECTED']
        example: 'APPROVED'
      description:
        type: string
        example: '8월 급여'

  ExpenseRequest:
    type: object
    required:
      - date
      - amount
      - category
    properties:
      date:
        type: string
        format: date
        example: '2025-08-11'
      amount:
        type: integer
        example: 600000
      category:
        type: string
        enum: ['LIVING_EXPENSES', 'FIXED_EXPENSES', 'LEISURE']
        example: 'LEISURE'
      paymentMethod:
        type: string
        enum: ['BANK_TRANSFER', 'CASH', 'CREDIT_CARD', 'DEBIT_CARD']
        example: 'CREDIT_CARD'
      status:
        type: string
        enum: ['APPROVED', 'SCHEDULED', 'REJECTED']
        example: 'APPROVED'
      description:
        type: string
        example: '티켓 예매'

  TargetSpendingRequest:
    type: object
    required:
      - year
      - month
      - category
      - amount
    properties:
      year:
        type: integer
        example: 2025
      month:
        type: integer
        example: 8
      category:
        type: string
        enum: ['LIVING_EXPENSES', 'FIXED_EXPENSES', 'LEISURE']
        example: 'LIVING_EXPENSES'
      amount:
        type: integer
        example: 500000
      description:
        type: string
        example: '이번 달 생활비 50만원 이하'
        
  CreateChallengeRequest:
    type: object
    required:
      - title
      - rewardXp
      - challengeType
      - targetValue
    properties:
      title:
        type: string
        example: '일주일 지출 10회 미만'
      description:
        type: string
        example: '일주일 동안 지출 횟수를 10회 미만으로 유지하여 절약 습관을 길러보세요.'
      rewardXp:
        type: integer
        example: 100
      challengeStartDate:
        type: string
        format: date
        example: '2025-11-10'
      challengeExpireDate:
        type: string
        format: date
        example: '2025-11-17'
      limitDay:
        type: integer
        example: 7
      challengeType:
        type: string
        enum:
          - EXPENSE_COUNT_MORE
          - EXPENSE_COUNT_LESS
          - INCOME_COUNT_MORE
          - INCOME_COUNT_LESS
          - EXPENSE_TOTAL_AMOUNT_LESS
          - EXPENSE_TOTAL_AMOUNT_MORE
          - INCOME_TOTAL_AMOUNT_LESS
          - INCOME_TOTAL_AMOUNT_MORE
        example: 'EXPENSE_COUNT_LESS'
      targetValue:
        type: integer
        example: 10
        
  UpdateChallengeRequest:
    type: object
    properties:
      title:
        type: string
        example: '일주일 지출 5회 미만'
      description:
        type: string
        example: '절약 챌린지 난이도 상승!'
      rewardXp:
        type: integer
        example: 150
      challengeStartDate:
        type: string
        format: date
        example: '2025-12-01'
      challengeExpireDate:
        type: string
        format: date
        example: '2025-12-08'
      limitDay:
        type: integer
        example: 7
      challengeType:
        type: string
        enum:
          - EXPENSE_COUNT_MORE
          - EXPENSE_COUNT_LESS
          - INCOME_COUNT_MORE
          - INCOME_COUNT_LESS
          - EXPENSE_TOTAL_AMOUNT_LESS
          - EXPENSE_TOTAL_AMOUNT_MORE
          - INCOME_TOTAL_AMOUNT_LESS
          - INCOME_TOTAL_AMOUNT_MORE
        example: 'EXPENSE_COUNT_LESS'
      targetValue:
        type: integer
        example: 5

  Challenge:
    type: object
    properties:
      challengeId:
        type: integer
      title:
        type: string
      description:
        type: string
        nullable: true
      rewardXp:
        type: integer
      challengeStartDate:
        type: string
        format: date
        nullable: true
      challengeExpireDate:
        type: string
        format: date
        nullable: true
      challengeType:
        type: string
        enum:
          - EXPENSE_COUNT_MORE
          - EXPENSE_COUNT_LESS
          - INCOME_COUNT_MORE
          - INCOME_COUNT_LESS
          - EXPENSE_TOTAL_AMOUNT_LESS
          - EXPENSE_TOTAL_AMOUNT_MORE
          - INCOME_TOTAL_AMOUNT_LESS
          - INCOME_TOTAL_AMOUNT_MORE
        nullable: true
      targetValue:
        type: integer
        nullable: true
      limitDay:
        type: integer
        nullable: true
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: [string, 'null']
        format: date-time
        nullable: true

  ChallengeChecklist:
    type: object
    properties:
      challengeChecklistId:
        type: integer
      userId:
        type: integer
      challengeId:
        type: integer
      status:
        type: string
        enum: ['PENDING', 'COMPLETED', 'FAILED']
      userStartDate:
        type: string
        format: date-time
      userExpireDate:
        type: string
        format: date-time
      completeDate:
        type: string
        format: date-time
        nullable: true
      challenge:
        $ref: '#/schemas/Challenge'
      createdAt:
        type: string
        format: date-time
        example: '2025-11-10T00:00:00Z'
      updatedAt:
        type: string
        format: date-time
        example: '2025-11-10T00:00:00Z'
      deletedAt:
        type: [string, 'null']
        format: date-time
        nullable: true
        example: null

  CreateChallengeChecklistRequest:
    type: object
    required:
      - challengeId
    properties:
      challengeId:
        type: integer
        description: 참여할 챌린지의 ID

  GetChallengeChecklistsResponse:
    type: object
    properties:
      checklists:
        type: array
        items:
          $ref: '#/schemas/ChallengeChecklist'
      totalItems:
        type: integer

  UserChallengeStatus:
    type: object
    properties:
      challengeId:
        type: integer
      title:
        type: string
      description:
        type: string
      rewardXp:
        type: integer
      status:
        type: string
        enum: ['PENDING', 'COMPLETED']
      achievedAt:
        type: string
        format: date

  User:
    type: object
    properties:
      userId:
        type: integer
      nickname:
        type: string
      contactEmail:
        type: string
        format: email
      profileImageUrl:
        type: string
        format: uri
      gender:
        type: string
        enum: ['male', 'female']
      birthday:
        type: string
        format: date
      status:
        type: string
        enum: ['active', 'inactive', 'blocked']
      role:
        type: string
        enum: ['user', 'admin']
      level:
        type: integer
      exp:
        type: integer





  UserUpdatePayload:
    type: object
    properties:
      nickname:
        type: string
      contactEmail:
        type: string
        format: email
      profileImageUrl:
        type: string
        format: uri
      gender:
        type: string
        enum: ['male', 'female']
      role:
        type: string
        enum: ['user', 'admin']



  UserLog:
    type: object
    properties:
      logId:
        type: integer
      userId:
        type: integer
      actionType:
        type: string
      details:
        type: object
      traceId:
        type: string
        format: uuid
      createdAt:
        type: string
        format: date-time
      User:
        type: object
        properties:
          nickname:
            type: string
          email:
            type: string
          role:
            type: string

  GetLogsResponse:
    type: object
    properties:
      count:
        type: integer
      rows:
        type: array
        items:
          $ref: '#/schemas/UserLog'

  GetChallengesResponse:
    type: object
    properties:
      challenges:
        type: array
        items:
          $ref: '#/schemas/Challenge'
      totalItems:
        type: integer
        
  UserProfile:
    type: object
    properties:
      nickname:
        type: string
      contactEmail:
        type: string
        format: email
      profileImageUrl:
        type: [string, 'null']
        nullable: true
      gender:
        type: string
        enum: ['male', 'female']
      birthday:
        type: string
        format: date
      level:
        type: integer
      exp:
        type: integer

  Income:
    type: object
    properties:
      incomeId:
        type: integer
      userId:
        type: integer
      financialYearId:
        type: integer
      date:
        type: string
        format: date
      amount:
        type: integer
      category:
        type: string
        enum: ['SALARY', 'SIDE_INCOME', 'ALLOWANCE']
      status:
        type: string
        enum: ['APPROVED', 'SCHEDULED', 'REJECTED']
      description:
        type: string
      createdAt:
        type: string
        format: date-time
        example: '2025-08-10T10:00:00Z'
      updatedAt:
        type: string
        format: date-time
        example: '2025-08-10T10:00:00Z'
      deletedAt:
        type: [string, 'null']
        format: date-time
        nullable: true
        example: null

  Expense:
    type: object
    properties:
      expenseId:
        type: integer
      userId:
        type: integer
      financialYearId:
        type: integer
      date:
        type: string
        format: date
      amount:
        type: integer
      category:
        type: string
        enum: ['LIVING_EXPENSES', 'FIXED_EXPENSES', 'LEISURE']
      status:
        type: string
        enum: ['APPROVED', 'SCHEDULED', 'REJECTED']
      description:
        type: string
      createdAt:
        type: string
        format: date-time
        example: '2025-08-11T10:00:00Z'
      updatedAt:
        type: string
        format: date-time
        example: '2025-08-11T10:00:00Z'
      deletedAt:
        type: [string, 'null']
        format: date-time
        nullable: true
        example: null

  TargetSpending:
    type: object
    properties:
      targetSpendingId:
        type: integer
      userId:
        type: integer
      financialYearId:
        type: integer
      category:
        type: string
        enum: ['LIVING_EXPENSES', 'FIXED_EXPENSES', 'LEISURE']
      amount:
        type: integer
      description:
        type: string
        
  ReportType:
    type: object
    properties:
      reportTypeId:
        type: integer
      type:
        type: string
        enum:
          - MONTHLY_TOTAL_INCOME
          - MONTHLY_TOTAL_EXPENSE
          - PREV_MONTH_EXPENSE_CHANGE
          - PREV_MONTH_INCOME_CHANGE
          - EXPENSE_RATIO_BY_CATEGORY
          - INCOME_RATIO_BY_CATEGORY
      unit:
        type: string
        enum:
          - WON
          - PERCENT
          - COUNT
  Report:
    type: object
    properties:
      reportId:
        type: integer
      userId:
        type: integer
      financialYearId:
        type: integer
      reportTypeId:
        type: integer
      value:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      ReportType:
        $ref: '#/schemas/ReportType'
  GetReportsResponse:
    type: object
    properties:
      reports:
        type: array
        items:
          $ref: '#/schemas/Report'

  HealthStatusResponse:
    type: object
    properties:
      server:
        type: object
        properties:
          status:
            type: string
            enum: ['OK', 'FAIL']
            example: 'OK'
          uptime:
            type: number
            example: 123.45
      database:
        type: object
        properties:
          status:
            type: string
            enum: ['OK', 'FAIL', 'UNKNOWN']
            example: 'OK'
      redis:
        type: object
        properties:
          status:
            type: string
            enum: ['OK', 'FAIL', 'UNKNOWN']
            example: 'OK'

  MessageResponse:
    type: object
    properties:
      message:
        type: string
        example: "성공적으로 삭제되었습니다."
